#!/bin/sh

cat <<'_EOF'
           .-='-. _db_      .--==-,
          (_  (  _IIII_   _(    )  `.
            (    |" " |-.(  ` ,_  `  )
             '-._HHHHHH  `)---' `'--'
                 |.   |--`
                 |    |      Lighthouse Labs
       _H___,=====;___|      Built # {{ pillar['build_date'] }}-{{ pillar['build_hash'] }}
    n_/____/____/``\__\
   /__|:: :|. .|:::|::|      Direct complaints to /dev/null
_%&|__&%_"_|_"_|_ H|__|__
_EOF
